packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@swc/core': true
  'electron-winstaller': true
  'esbuild': true
  'sharp': true
  'workerd': true

configDependencies:
  '@pnpm/pacquet': 0.11.12
