use gpui::actions;

actions!(
    mdow,
    [
        NewWindow,
        OpenFile,
        OpenFolder,
        ToggleSidebar,
        CloseTab,
        ToggleWideMode,
        Quit,
        ToggleFind,
        TogglePalette,
        ToggleSettings,
        ToggleShortcuts,
        Dismiss,
        FindNext,
        FindPrevious,
        ZoomIn,
        ZoomOut,
        ZoomReset,
        SidebarRecents,
        SidebarFolder,
        SidebarOutline,
        CheckForUpdates,
        NextTab,
        PreviousTab,
        SelectTab1,
        SelectTab2,
        SelectTab3,
        SelectTab4,
        SelectTab5,
        SelectTab6,
        SelectTab7,
        SelectTab8,
        SelectLastTab
    ]
);
